config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms, except: :index
  resources :messages, only: %i[ new create ]
  resources :profiles, only: :show do
    member do
      post :upload_avatar
      delete :purge_avatar
    end
  end
  namespace :admin do
    resources :messages, only: %i[ new create ]
    resources :homepagesses, except: :index
    resources :abouts, except: %i[ show new ]
    resources :user_lists, except: :show
    resources :products do
      collection do
        match 'search' => 'products#search', via: [:get, :post], as: :search
      end
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
    end
    post 'faileds/removecart'
    post 'faileds/removebucket'
    post 'histories/add'
    post 'histories/remove'
    post 'faileds/add_cart'
    post 'faileds/add_bucket'
    post 'bucket/add'
    post 'bucket/remove'
    get 'failed', to: 'faileds#show'
    get 'bucket', to: 'bucket#show'
    get 'history', to: 'histories#show'
    get 'pages/dashboard'
    get 'pages/customer'
    get 'pages/adminlist'
    get 'pages/order'
    get 'pages/message'
    get 'pages/newadmin'
    get 'pages/chatroom/:chatroom_id', to: 'pages#chatroom', as: :chatroom
    get 'pages/chatbox', to: 'pages#chatbox', as: :chatbox
    patch "pages/adminlist/:id", to: "pages#add_admin"
    patch "products/stock/:id", to: "products#stock", as: :stock
    patch "products/preorder/:id", to: "products#preorder", as: :preorder
  end
  resources :products, only: %i[ show index ] do
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
      member do
        patch "upvote", to: "products#upvote"
      end
  end
  post 'faileds/add'
  post 'cart/cart_update'
  post 'cart/addcart'
  post 'cart/add'
  post 'cart/removecart'
  post 'cart/remove'
  post 'cart/delete'
  get 'failed', to: 'faileds#show'
  get 'bucket', to: 'bucket#show'
  get 'history', to: 'histories#show'
  get 'cart', to: 'cart#show'
  get 'comments/comment'
  get 'pages/about'
  get 'pages/home'
  root 'pages#home'
  mount ActionCable.server, at: '/cable'
end

app/views/admin/pages/_customer.html.erb
<% obj.order(id: :desc).where(admin: :false).each do |customer| %>
    <%# <% if !customer.orderables.empty? %>
    <%# <% if !customer.orderables.empty? || !customer.vessels.empty? || !customer.keeps.empty? || !customer.faileds.empty? %>
    <% if !customer.orderables.empty? || !customer.vessels.empty? || !customer.keeps.empty? || !customer.faileds.empty? %>
        <tr>
            <td><%= customer.username %></td>
            <td><%= customer.orderables.count %> <%= customer.orderables.count <= 1 ? 'product' : 'products' %></td>
            <td><%= customer.vessels.count %> <%= customer.vessels.count <= 1 ? 'product' : 'products' %></td>
            <td><%= customer.keeps.count %> <%= customer.keeps.count <= 1 ? 'product' : 'products' %></td>
            <td><%= customer.faileds.count %> <%= customer.faileds.count <= 1 ? 'product' : 'products' %></td>
            <%# <td><%= link_to 'Detail', profile_path(customer), class:"btn btn-sm btn-primary" %>
        </tr>
    <% end %>
<% end %>

app/views/admin/pages/_dashboard.html.erb
<!-- content -->
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <%# <li class="breadcrumb-item active">Dashboard</li> %>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body"><%= Homepagess.count == 0 ? 'Create Home Page' : 'Edit Home Page' %></div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="<%= Homepagess.count == 0 ? new_admin_homepagess_path : admin_homepagess_path(Homepagess.first) %>">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-warning text-white mb-4">
                <div class="card-body"><%= About.count == 0 ? 'Create About Page' : 'Edit About Page' %></div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="<%= admin_abouts_path %>">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">Messages <span class="badge text-bg-light rounded-pill"><%= @chatboxes.count %></span></div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="<%= admin_chatbox_path %>">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body">Admin Lists</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="<%= admin_pages_newadmin_path %>">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-area me-1"></i>
                    Amount of sold product
                </div>
                <div class="card-body">
                    <%# <%= line_chart Keep.group_by_day(:created_at, range: 1.month.ago.midnight..Time.now).sum(:quantity) %>
                    <%# <%= column_chart Keep.group_by_day_of_week(:created_at, format: "%a", range: 1.month.ago.midnight..Time.now).sum(:quantity) %>
                    <%# <%= column_chart Keep.group_by_day(:created_at, format: "%b", range: 6.month.ago.midnight..Time.now).sum(:quantity) %>
                    <%= column_chart Keep.group_by_day(:created_at, format: "%b", range: 6.month.ago.midnight..Time.now, time_zone: false).sum(:quantity), suffix: " piece" %>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-bar me-1"></i>
                    Sales results
                </div>
                <div class="card-body">
                <%# <canvas id="myBarChart" width="100%" height="40"> %>
                    <%# <%= line_chart Product.group_by_day(:created_at, range: 1.month.ago.midnight..Time.now).sum(:price) %>
                    <%# <%= area_chart Keep.group_by_day(:created_at, range: 1.month.ago.midnight..Time.now).sum(:total_price) %>
                    <%= area_chart Keep.group_by_day(:created_at, range: 1.month.ago.midnight..Time.now, time_zone: false).sum(:total_price), prefix: "Rp. ", thousands: ".", decimal: "," %>
                <%# </canvas> %>
                </div>
            </div>
        </div>
    </div>
    <%#  %>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            The most favorite product
        </div>
        <div class="card-body">
            <%# table %>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Likes</th>
                            <th scope="col">Sold</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @products.order(cached_votes_score: :desc).each_with_index do |product, index| %>
                            <% if index < 5 %>
                                <tr>
                                    <td><%= index + 1 %></td>
                                    <td><%= link_to product.name, product, class: "text-decoration-none text-dark" %></td>
                                    <td><%= number_to_currency(product.price, unit: "Rp. ", separator: ",", delimiter: ".") %></td>
                                    <td><%= product.cached_votes_score %></td>
                                    <td><%= product.keeps.count %></td>
                                </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <%# end table %>
        </div>
    </div>
    <%#  %>
</div>
<!-- content -->

<%#  %>

app/views/admin/pages/_newadmin.html.erb
<% obj.order(id: :desc).each do |customer| %>
    <tr>
        <% if customer.admin? %>
            <td>
                Admin
            </td>
        <% else %>
            <td>
                User
            </td>
        <% end %>
        <td><%= customer.email %></td>
        <td><%= time_ago_in_words(customer.created_at) %></td>
        <td>
            <% unless customer.id == current_user.id %>
                <%= link_to customer.admin == true ? "User" : "Admin", admin_path(customer), method: :patch, class:customer.admin == true ? "btn btn-warning" : "btn btn-danger" %>
            <% end %>
        </td>
    </tr>
<% end %>

app/views/admin/pages/_useradmin.html.erb
<% obj.order(id: :desc).where(admin: :true).each do |customer| %>
    <tr>
        <% if customer.admin? %>
            <td>
                Admin
            </td>
        <% else %>
            <td>
                Customer
            </td>
        <% end %>
        <td><%= customer.email %></td>
        <td><%= time_ago_in_words(customer.created_at) %></td>
        <td>Test</td>
    </tr>
<% end %>

app/views/admin/pages/adminlist.html.erb
<div class="container-fluid px-4">
    <h2 class="mt-4">Section title</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Role</th>
                    <th scope="col">Name</th>
                    <th scope="col">Join</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <%= render 'admin/pages/useradmin', obj: @customers %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/pages/chatbox.html.erb
<div class="container-fluid px-4">
    <h2 class="mt-4 mb-2">All Chat</h2>
    <div class="list-group">
      <% @chatboxes.order(id: :desc).each do |chatbox| %>
        <a href="<%= admin_chatroom_path(chatbox) %>" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">From: <%= chatbox.user.username %></h5>
            <small><%= time_ago_in_words(chatbox.created_at) %> ago</small>
          </div>
          <p class="mb-1"><%= chatbox.topic %></p>
          <%# <small>And some small print.</small> %>
        </a>
      <% end %>
    </div>
</div>

<div class="mt-2 d-flex justify-content-center">
  <%= paginate @chatboxes %>
</div>
<div class="text-center">
  <%= page_entries_info @chatboxes, entry_name: 'chat' %>
</div>

app/views/admin/pages/chatroom.html.erb
<div class="container mt-4 mb-4">
    <div class="card">
        <div class="card-body">

            <h1>Chat room: <%= @chatroom.topic %></h1>

            <div class="card bg-light p-3">
                <div id="message_container">
                    <div id="message_holder">
                        <%# <%= render @messages %>
                        <%= render @messages %>
                    </div>
                </div>

                <%# <%= form_for @message, remote: true do |f| %>
                <%= form_for @message, url: admin_messages_path, remote: true do |f| %>
                <div class="input-group mb-3 p-2 bg-dark rounded">
                    <%= f.hidden_field :chatroom_id, value: @chatroom.id %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.text_field :content, class:"form-control", placeholder:"Type here..." %>
                    <%= f.submit class:"btn btn-success", style:"display:none;" %> 
                </div>
                <% end %>
            </div>

        </div>
    </div>
</div>

app/views/admin/pages/customer.html.erb
<div class="container-fluid px-4">
    <h2 class="mt-4">Customer on Process</h2>

    <%#  %>
    <div class="row mb-2">
        <div class="col">
            <%= page_entries_info @customers, entry_name: 'customer' %>
        </div>
        <div class="col">
            <%# <% if User.count > 25 %>
            <div class="d-flex flex-row-reverse">
                <div class="btn-group border">
                    <%= link_to " ", (path_to_prev_page @customers), class: @customers.first_page? ? "btn btn-dark bi bi-chevron-left disabled" : "btn btn-dark bi bi-chevron-left" %>
                    <%= link_to " ", (path_to_next_page @customers), class: @customers.last_page? ? "btn btn-dark bi bi-chevron-right disabled" : "btn btn-dark bi bi-chevron-right" %>
                </div>
            </div>
            <%# <% end %>
        </div>
    </div>
    <%#  %>
    <div class="table-responsive">
        <table class="table table-striped table-sm table-hover">
            <thead>
                <tr>
                    <th scope="col">Username</th>
                    <th scope="col">Total order</th>
                    <th scope="col">Production process</th>
                    <th scope="col">Success</th>
                    <th scope="col">Failed process</th>
                    <%# <th scope="col">Action</th> %>
                </tr>
            </thead>
            <tbody>
                <%= render 'admin/pages/customer', obj: @customers %>
            </tbody>
        </table>
    </div>
</div>


app/views/admin/pages/dashboard.html.erb
<%= render 'admin/pages/dashboard' %>

app/views/admin/pages/newadmin.html.erb
<div class="container-fluid px-4">
    <h2 class="mt-4">Add new admin</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm table-hover">
            <thead>
                <tr>
                    <th scope="col">Role</th>
                    <th scope="col">Name</th>
                    <th scope="col">Join</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <%= render 'admin/pages/newadmin', obj: @customers %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/pages/order.html.erb
<div class="container-fluid px-4">
    <h2 class="mt-4">
        Order page
    </h2>

    <div class="row mb-2">
        <div class="col">
            <%= page_entries_info @orders, entry_name: 'processed order' %>
        </div>
        <div class="col">
            <% if Orderable.count > 25 %>
            <div class="d-flex flex-row-reverse">
                <div class="btn-group border">
                    <%= link_to " ", (path_to_prev_page @orders), class: @orders.first_page? ? "btn btn-dark bi bi-chevron-left disabled" : "btn btn-dark bi bi-chevron-left" %>
                    <%= link_to " ", (path_to_next_page @orders), class: @orders.last_page? ? "btn btn-dark bi bi-chevron-right disabled" : "btn btn-dark bi bi-chevron-right" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
<%# table %>
<div class="table-responsive">
    <table class="table table-hover table-striped table-bordered table-sm">
        <thead class="table-light">
            <tr>
                <th scope="col" class="text-center">
                <%# No. %>
                </th>
                <th scope="col">Customer</th>
                <th scope="col" class="text-center">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
                <th scope="col">Order Time</th>
                <th scope="col">Due Date</th>
                <th scope="col" class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @orders.order(id: :desc).each_with_index do |order, index| %>
                <%# <% if !order.images.empty? %>
                <% product = order.product %>
                    <% user = order.user %>
                        <tr>
                            <td class="text-center">
                                <%# <%= index + 1 %>
                                <i class="bi bi-dot"></i>
                            </td>
                            <td><%= user.username %></td>
                            <td class="text-center">
                                <%# <a data-bs-toggle="modal" href="#Modal %>
                                <%# <%= index %>
                                <%# "> %>
                                <a href="<%= admin_product_path(product) %>">
                                    <% if product.images.attached? %>
                                        <% product.images.each_with_index do |image, idx| %>
                                            <% if idx == 0 %>
                                                <%# <%= image_tag(image, class:"img-thumbnail", width:50) %>
                                                <% if image.image? %>
                                                    <%= image_tag image, class:"img-thumbnail", width:50 %>
                                                <% elsif image.video? %>
                                                    <video class="img-thumbnail" style="width:50px;">
                                                        <source src="<%= rails_blob_url(image) %>" type="<%= image.content_type %>"/>
                                                    </video>
                                                <% else %>
                                                    Download: <%= link_to image.filename, rails_blob_path(image, disposition: "file") %>
                                                <% end %>
                                                <%#  %>
                                            <% end %>
                                        <% end %>
                                    <% else %>
                                        <%= image_tag("https://lpm.ulm.ac.id/image/desain/empty.jpg", class:"img-thumbnail", width:50) %>
                                    <% end %>
                                </a>
                            </td>
                                <td><%= truncate(product.name, length: 20) %></td>
                                <td>
                                    <%= number_to_currency(product.price, unit: "Rp. ", separator: ",", delimiter: ".") %>
                                </td>
                                <td><%= order.quantity %></td>
                                <td>
                                    <%= number_to_currency(product.price * order.quantity, unit: "Rp. ", separator: ",", delimiter: ".") %>
                                </td>
                                <td>
                                <%= order.created_at.strftime("%d/%m/%y") %>
                                <%# <%= time_ago_in_words(order.created_at) %>
                                </td>
                                <td>
                                <%#  %>
                                <%= form_with(url: admin_histories_add_path) do |f| %>
                                    <%= f.hidden_field :id, value: order.id %>
                                    <%= f.hidden_field :price, value: product.price * order.quantity %>
                                    <%= f.hidden_field :quantity, value: order.quantity %>
                                    <%= f.hidden_field :order_at, value: order.created_at.strftime("%d/%m/%y") %>
                                    <%= f.hidden_field :customer, value: user.username %>
                                    <%= f.hidden_field :product_name, value: product.name %>
                                    <%= f.hidden_field :product_price, value: product.price %>
                                    <%= f.hidden_field :point, value: product.id %>
                                    <%= f.hidden_field :product_id, value: product.id %>
                                    <%= f.hidden_field :user_id, value: order.user.id %>
                                    <%= f.hidden_field :description, value: order.description %>
                                    
                                    <div class="form-floating mb-1">
                                        <%= f.date_field :date, class: "form-control" %>
                                        <label for="floatingInput">Due date</label>
                                    </div>
                                    <div class="d-grid gap-2">
                                        <%= f.submit "Process", class: order.images.empty? ? "btn btn-dark disabled" : "btn btn-dark" %>
                                    </div>
                                <% end %>
                                </td>
                                <td class="text-center">
                                    <%= form_with(url: admin_faileds_add_cart_path) do |f| %>
                                        <%= f.hidden_field :id, value: order.id %>
                                        <%= f.hidden_field :total_price, value: product.price * order.quantity %>
                                        <%= f.hidden_field :quantity, value: order.quantity %>
                                        <%= f.hidden_field :order_start, value: order.created_at.strftime("%d/%m/%y") %>
                                        <%= f.hidden_field :customer, value: user.username %>
                                        <%= f.hidden_field :product_name, value: product.name %>
                                        <%= f.hidden_field :product_price, value: product.price %>
                                        <%= f.hidden_field :product_id, value: product.id %>
                                        <%= f.hidden_field :description, value: order.description %>
                                        <%# <%= f.hidden_field :point, value: product.id %> 
                                        <%= f.hidden_field :user_id, value: order.user.id %>
                                        <%= f.submit "Cancel", class: "btn btn-dark btn-sm mb-1", data: { confirm: "Are you sure?" } %>
                                    <% end %>
                                    <% if !order.description.empty? %>
                                    <!-- Button trigger modal -->
                                    <div class="mb-1">
                                        <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#Modal<%= index %>">
                                            Notes
                                        </button>
                                    </div>
                                    <% end %>
                                    <% if !order.images.empty? %>
                                    <div>
                                        <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#Slip<%= index %>">
                                            Slip
                                        </button>
                                    </div>
                                    <% end %>
                                </td>
                            </tr>
                        <%# <% end %>
                        <% end %>
                        <tr class="table-warning">
                            <td colspan="5">
                                <strong>Total</strong>
                            </td>
                            <td class="table-danger">
                                <strong>
                                    <%= @orders.to_a.sum { |orderable| orderable.quantity } %>
                                </strong>
                            </td>
                            <td class="table-danger">
                                <strong>
                                    <%= number_to_currency(@orders.to_a.sum { |orderable| orderable.total }, unit: "Rp. ", separator: ",", delimiter: ".") %>
                                </strong>
                            </td>
                            <td>
                            </td>
                            <td>
                            </td>
                            <td> </td>
                        </tr>
                    </tbody>
                </table>
            </div>
<%# end table %>
</div>


<% @orders.order(id: :desc).each_with_index do |order, index| %>
<!-- Modal -->
<div class="modal fade" id="Modal<%= index %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_format(order.description) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Modal Slip -->
<div class="modal fade" id="Slip<%= index %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% if order.images.attached? %>
            <% order.images.each do |image| %>
                <%= image_tag(image, class:'w-100') %>
            <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>