config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms, except: :index
  resources :messages, only: %i[ new create ]
  resources :profiles, only: :show do
    member do
      post :upload_avatar
      delete :purge_avatar
    end
  end
  namespace :admin do
    resources :messages, only: %i[ new create ]
    resources :homepagesses, except: :index
    resources :abouts, except: %i[ show new ]
    resources :user_lists, except: :show
    resources :products do
      collection do
        match 'search' => 'products#search', via: [:get, :post], as: :search
      end
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
    end
    post 'faileds/removecart'
    post 'faileds/removebucket'
    post 'histories/add'
    post 'histories/remove'
    post 'faileds/add_cart'
    post 'faileds/add_bucket'
    post 'bucket/add'
    post 'bucket/remove'
    get 'failed', to: 'faileds#show'
    get 'bucket', to: 'bucket#show'
    get 'history', to: 'histories#show'
    get 'pages/dashboard'
    get 'pages/customer'
    get 'pages/adminlist'
    get 'pages/order'
    get 'pages/message'
    get 'pages/newadmin'
    get 'pages/chatroom/:chatroom_id', to: 'pages#chatroom', as: :chatroom
    get 'pages/chatbox', to: 'pages#chatbox', as: :chatbox
    patch "pages/adminlist/:id", to: "pages#add_admin"
    patch "products/stock/:id", to: "products#stock", as: :stock
    patch "products/preorder/:id", to: "products#preorder", as: :preorder
  end
  resources :products, only: %i[ show index ] do
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
      member do
        patch "upvote", to: "products#upvote"
      end
  end
  post 'faileds/add'
  post 'cart/cart_update'
  post 'cart/addcart'
  post 'cart/add'
  post 'cart/removecart'
  post 'cart/remove'
  post 'cart/delete'
  get 'failed', to: 'faileds#show'
  get 'bucket', to: 'bucket#show'
  get 'history', to: 'histories#show'
  get 'cart', to: 'cart#show'
  get 'comments/comment'
  get 'pages/about'
  get 'pages/home'
  root 'pages#home'
  mount ActionCable.server, at: '/cable'
end

app/controllers/admin/homepagesses_controller.rb
module Admin
  class HomepagessesController < ApplicationController
    before_action :set_homepagess, only: %i[ show edit update destroy ]
    before_action :authenticate_user!
    before_action :restrict_user_by_role
    before_action :only_one_row_record, only: %i[ new create ]

    # GET /homepagesses/1 or /homepagesses/1.json
    def show
      @records = Homepagess.all
    end

    # GET /homepagesses/new
    def new
      @homepagess = Homepagess.new
    end

    # GET /homepagesses/1/edit
    def edit
    end

    # POST /homepagesses or /homepagesses.json
    def create
      @homepagess = Homepagess.new(homepagess_params)

      respond_to do |format|
        if Homepagess.count > 0
          format.html { redirect_to admin_homepagess_url(Homepagess.first), notice: "You can create only one row of this table" }
          format.json { render :show, status: :created, location: @homepagess }
        else
          if @homepagess.save
            format.html { redirect_to admin_homepagess_url(@homepagess), notice: "Homepagess was successfully created." }
            format.json { render :show, status: :created, location: @homepagess }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @homepagess.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    # PATCH/PUT /homepagesses/1 or /homepagesses/1.json
    def update
      respond_to do |format|
        if @homepagess.update(homepagess_params)
          format.html { redirect_to admin_homepagess_url(@homepagess), notice: "Homepagess was successfully updated." }
          format.json { render :show, status: :ok, location: @homepagess }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @homepagess.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /homepagesses/1 or /homepagesses/1.json
    def destroy
      @homepagess.destroy

      respond_to do |format|
        format.html { redirect_to new_admin_homepagess_url, notice: "Homepagess was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      def only_one_row_record
          redirect_to admin_homepagess_url(Homepagess.first), notice: "You can create only one row of this table" if Homepagess.count > 0
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_homepagess
        @homepagess = Homepagess.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def homepagess_params
        params.require(:homepagess).permit(:brand_name, :title, :description, covers: [])
      end
    
    protected
    # redirect if user not logged in or does not have a valid role
      def restrict_user_by_role
        redirect_to root_path, notice: "You're not authorized!" if current_user.admin == false
      end
  end
end

app/helpers/homepagesses_helper.rb
module HomepagessesHelper
end

app/views/admin/homepagesses/_form.html.erb
<%= form_with model: [:admin, @homepagess] do |form| %>
  <% if homepagess.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <div id="error_explanation">
      <h2><%= pluralize(homepagess.errors.count, "error") %> prohibited this homepagess from being saved:</h2>
      <ul>
        <% homepagess.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>

    <% if @homepagess.covers.attached? %>
      <% @homepagess.covers.each_with_index do |cover, index| %>
        <% if index < 1 %>
          <header class="masthead bg-dark" style="background-image: linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.45)), url('<%= cover.url %>');background-repeat: no-repeat;background-attachment: scroll;background-position: center center;background-size: cover;">
        <% end %>
      <% end %>
    <% else %>
      <header class="masthead bg-dark" style="background-image: linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.45)), url('https://deneenpottery.com/wp-content/uploads/2018/09/what-about-pottery-resonates-so-much.jpg');background-repeat: no-repeat;background-attachment: scroll;background-position: center center;background-size: cover;">
    <% end %>
    <%# <header class="masthead bg-dark" style="background-image: linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.45)), url('https://deneenpottery.com/wp-content/uploads/2018/09/what-about-pottery-resonates-so-much.jpg');background-repeat: no-repeat;background-attachment: scroll;background-position: center center;background-size: cover;"> %>

    <div class="container">
        <div class="mb-2">
          <h3>
            <%= form.label :covers, 'Images Carousel', class:"form-label" %>
          </h3>
          <%= form.file_field :covers, accept:"image/*", multiple: true, class:"form-control", direct_upload: true %>
        </div>
        <%# <div class="masthead-subheading"> %>
        <div class="form-floating mb-2 text-dark">
          <%= form.text_field :brand_name, class:"form-control", placeholder:"Text" %>
          <%= form.label :brand_name, 'Text', class:"form-label" %>
        </div>
        <%# </div> %>
        <%# <div class="masthead-heading text-uppercase"> %>
        <div class="form-floating height-form-text mb-2 text-dark">
          <%= form.text_field :description, class:"form-control", placeholder:"Description"  %>
          <%= form.label :description, class:"form-label", placeholder:"desc" %>
        </div>
        <%# </div> %>
        <%= link_to 'Tell Me More', pages_about_path, class:"btn btn-primary btn-lg text-uppercase disabled" %>
    </div>
</header>

<div class="p-5 mb-4 bg-light bg-opacity-50">
    <div class="container-fluid py-5">
        <%# <h1 class="col-md-8 display-5 fw-bold">
            Let's find your pottery!
        </h1> %>
        <div class="form-floating mb-2">
          <%= form.text_field :title, class:"form-control", placeholder:"name" %>
          <%= form.label :title, 'Text', class:"form-label", placeholder:"Text" %>
        </div>
        <%= link_to "Shop now?", products_path, class:"btn btn-primary btn-lg disabled" %>
    </div>
    <div class="d-grid gap-2">
      <%= form.submit class:"btn btn-dark btn-lg" %>
      <%# <button class="btn btn-primary" type="button">Button</button> %>
    </div>
</div>
<% end %>

app/views/admin/homepagesses/_home.html.erb
<% if Homepagess.count == 0 %>
    <%# <header class="masthead bg-dark" style="background-image: url('https://deneenpottery.com/wp-content/uploads/2018/09/what-about-pottery-resonates-so-much.jpg');"> %>
    <header class="masthead bg-dark" style="background-image: linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.45)), url('https://media.istockphoto.com/id/1317091901/photo/five-ceramic-jugs.jpg?b=1&s=170667a&w=0&k=20&c=sUJ5lPK9QZtvB6wedX8Ns9SfY86BMpfCpC2duXAYm6s=');background-repeat: no-repeat;background-attachment: scroll;background-position: center center;background-size: cover;">
        <div class="container">
            <div style="text-shadow: 2px 4px 3px rgba(0,0,0,0.3);">
                <div class="masthead-subheading">Welcome To Our Gallery!</div>
                <div class="masthead-heading text-uppercase">It's Nice To Meet You</div>
            </div>
            <%= link_to 'Tell Me More', pages_about_path, class:"btn btn-primary btn-lg text-uppercase" %>
        </div>
    </header>
    
    <div class="p-5 mb-4 bg-light bg-opacity-50">
        <div class="container-fluid py-5">
            <h1 class="col-md-8 display-5 fw-bold">
                Let's find your pottery!
            </h1>
            <%= link_to "Shop now?", products_path, class:"btn btn-primary btn-lg" %>
        </div>
    </div>
<% else %>
<%#  %>
    <div class="position-relative">
        <% if @homepagess.covers.attached? %>
            <%= render 'pages/carousel', obj: @homepagess.covers %>
        <% else %>
            <%= render 'pages/carousel_empty' %>
        <% end %>
        
        <header class="masthead position-absolute top-50 start-50 translate-middle">
            <div class="container">
                <div style="text-shadow: 2px 4px 3px rgba(0,0,0,0.3);">
                    <%# <div class="masthead-subheading">Welcome To Our Gallery!</div>
                    <div class="masthead-heading text-uppercase">It's Nice To Meet You</div> %>
                    <div class="masthead-subheading"><%= @homepagess.brand_name %></div>
                    <div class="masthead-heading text-uppercase"><%= @homepagess.description %></div>
                </div>
                <%= link_to 'Tell Me More', pages_about_path, class: user_signed_in? && current_user.admin? ? "btn btn-primary btn-lg text-uppercase disabled" : "btn btn-primary btn-lg text-uppercase" %>
            </div>
        </header>
    </div>
    <div class="p-5 mb-4 bg-light bg-opacity-50">
        <div class="container-fluid py-5">
            <h1 class="col-md-8 display-5 fw-bold">
                <%= @homepagess.title %>
            </h1>
            <%= link_to "Shop now?", products_path, class: user_signed_in? && current_user.admin? ? "btn btn-primary btn-lg disabled" : "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>

app/views/admin/homepagesses/edit.html.erb
<div class="container-fluid px-4">
    <div class="card mb-3 mt-4 bg-light">
        <div class="card-body">
            <%= link_to 'Delete', admin_homepagess_path(@homepagess), class:"btn btn-lg
            btn-dark", method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to 'Back', :back, class:"btn btn-lg btn-dark
            float-end" %>
        </div>
    </div>
    <div class="mb-4 border border-secondary">
        <%= render 'form', homepagess: @homepagess %>
    </div>
</div>

app/views/admin/homepagesses/new.html.erb
<div class="container-fluid px-4">
    <h1 class="mt-4 mb-3">New Homepagess</h1>
    <div class="mb-4 border border-secondary">
        <%= render 'form', homepagess: @homepagess %>
    </div>
</div>

app/views/admin/homepagesses/show.html.erb
<div class="container-fluid px-4">
    <div class="card mb-3 mt-4 bg-light">
        <div class="card-body">
            <%= link_to 'Edit', edit_admin_homepagess_path(@homepagess), class:"btn btn-lg
            btn-dark" %>
            <%= link_to 'Delete', admin_homepagess_path(@homepagess), class:"btn btn-lg
            btn-dark", method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to 'Exit', admin_pages_dashboard_path, class:"btn btn-lg btn-dark
            float-end" %>
        </div>
    </div>
    <div class="mb-4 border border-secondary">
        <%= render 'admin/homepagesses/home' %>
    </div>
</div>