config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms, except: :index
  resources :messages, only: %i[ new create ]
  resources :profiles, only: :show do
    member do
      post :upload_avatar
      delete :purge_avatar
    end
  end
  namespace :admin do
    resources :messages, only: %i[ new create ]
    resources :homepagesses, except: :index
    resources :abouts, except: %i[ show new ]
    resources :user_lists, except: :show
    resources :products do
      collection do
        match 'search' => 'products#search', via: [:get, :post], as: :search
      end
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
    end
    post 'faileds/removecart'
    post 'faileds/removebucket'
    post 'histories/add'
    post 'histories/remove'
    post 'faileds/add_cart'
    post 'faileds/add_bucket'
    post 'bucket/add'
    post 'bucket/remove'
    get 'failed', to: 'faileds#show'
    get 'bucket', to: 'bucket#show'
    get 'history', to: 'histories#show'
    get 'pages/dashboard'
    get 'pages/customer'
    get 'pages/adminlist'
    get 'pages/order'
    get 'pages/message'
    get 'pages/newadmin'
    get 'pages/chatroom/:chatroom_id', to: 'pages#chatroom', as: :chatroom
    get 'pages/chatbox', to: 'pages#chatbox', as: :chatbox
    patch "pages/adminlist/:id", to: "pages#add_admin"
    patch "products/stock/:id", to: "products#stock", as: :stock
    patch "products/preorder/:id", to: "products#preorder", as: :preorder
  end
  resources :products, only: %i[ show index ] do
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
      member do
        patch "upvote", to: "products#upvote"
      end
  end
  post 'faileds/add'
  post 'cart/cart_update'
  post 'cart/addcart'
  post 'cart/add'
  post 'cart/removecart'
  post 'cart/remove'
  post 'cart/delete'
  get 'failed', to: 'faileds#show'
  get 'bucket', to: 'bucket#show'
  get 'history', to: 'histories#show'
  get 'cart', to: 'cart#show'
  get 'comments/comment'
  get 'pages/about'
  get 'pages/home'
  root 'pages#home'
  mount ActionCable.server, at: '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
    acts_as_votable
    belongs_to :user
    has_many_attached :images
    has_many :comments, dependent: :destroy
    has_many :orderables, dependent: :destroy
    has_many :carts, through: :orderables, dependent: :destroy

    # 
    has_many :vessels, dependent: :destroy
    has_many :keeps
    has_many :faileds
    # 

    validate :validate_images

    paginates_per 9

    validates :name, presence: true
    validates :price, presence: true

    # 
    # def set_quantity
    #     orderables.to_a.sum { |orderable| orderable.quantity }
    # end
    # 
  
    # extend FriendlyId
    # friendly_id :slug_candidates, use: [:slugged, :finders, :history]

    # def slug_candidates
    # [
    #     :name,
    #     [:name, :id]
    # ]
    # end

    # def should_generate_new_friendly_id?
    #     name_changed? || new_record? || slug.nil? || slug.blank?
    # end

    def new_method
        @order = orderables.first
        @order.images_status
    end

    private
    def validate_images
        return if images.count <= 10

        errors.add(:images, 'You can upload max 4 images')
    end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy stock preorder ]
    before_action :authenticate_user!
    before_action :restrict_user_by_role

    # GET /products or /products.json
    def index
      # @products = Product.all
      # @products = Product.order(cached_votes_score: :desc).page(params[:page])
      # 
      @q = Product.ransack(params[:q])
      @products = @q.result(distinct: true).order(cached_votes_score: :desc).page(params[:page])
    end

    def search
      index
      render :index
    end

    # GET /products/1 or /products/1.json
    def show
      # @keeps = Keep.all
      @keeps = @product.keeps.all
    end

    # GET /products/new
    def new
      @product = current_user.products.build
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = current_user.products.build(product_params)

      respond_to do |format|
        # 
        # if @product.images.count > 10
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json { render json: @product.errors, status: :unprocessable_entity }
        # else
        # 
          if @product.save
            format.html { redirect_to admin_product_url(@product), notice: "Product was successfully created." }
            format.json { render :show, status: :created, location: @product }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        # 
        # end
        # 
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        # 
        # if @product.images.count > 10
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json { render json: @product.errors, status: :unprocessable_entity }
        # else
        # 
          if @product.update(product_params)
            format.html { redirect_to admin_product_url(@product), notice: "Product was successfully updated." }
            format.json { render :show, status: :ok, location: @product }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        # 
        # end
        # 
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      # add_cart
      @product.destroy

      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def stock
      if @product.stock_product == true
        @product.update_attribute(:stock_product, false)
      elsif @product.stock_product == false
        @product.update_attribute(:stock_product, true)
      end
      redirect_to request.referrer
    end
    
    def preorder
      if @product.pre_order == true
        @product.update_attribute(:pre_order, false)
      elsif @product.pre_order == false
        @product.update_attribute(:pre_order, true)
      end
      redirect_to request.referrer
    end

    private
# 
    # def add_cart
    #   quantity = params[:quantity].to_i
    #   total_price = params[:total_price].to_i
    #   # order_end = params[:order_end].to_s
    #   order_start = params[:order_start].to_s
    #   customer = params[:customer].to_s
    #   product_price = params[:product_price].to_i
    #   product_name = params[:product_name].to_s
    #   product_id = params[:product_id].to_i 

    #   user_id = params[:user_id].to_i

    #   @failed = Failed.new(product_id: product_id, customer: customer, product_price: product_price, 
    #                        product_name: product_name, quantity: quantity, total_price: total_price,
    #                        order_start: order_start, user_id: user_id)
    #   if @failed.save
    #   #   removecart
    #   # else
    #     redirect_to request.referrer, notice: @failed.errors.full_messages.to_sentence
    #   end
    # end
# 

      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:name, :price, :description, images: [])
      end

    protected
    # redirect if user not logged in or does not have a valid role
      def restrict_user_by_role
        redirect_to root_path, notice: "You're not authorized!" if current_user.admin == false
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :upvote
  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).order(cached_votes_score: :desc).page(params[:page])
  end

  def upvote
  @product = Product.find(params[:id])
    if current_user.voted_up_on? @product
      @product.unvote_by current_user
    else
      @product.upvote_by current_user
    end
  render "vote.js.erb"
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    @keeps = @product.keeps.all
    # find current order in show page
    if user_signed_in?
      @showorder = @cart.orderables.find_by(product_id: @product.id)
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="row row-cols-1 row-cols-md-2 g-4">
  <% if params[:action] == "edit" %>
    <div class="col sticky-container">
      <%# <div class="sticky-2"> %>
      <div class="sticky-2 w-100 border shadow-sm rounded">
      <% if @product.images.attached? %>
        <div class="display-img-vid-con" id="img-vid-con">
          <%= render 'products/carousel_product', obj: @product.images %>
        </div>
      <% else %>
        <div class="display-img-vid-con" id="img-vid-con">
          <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel', id:"file-ip-1-preview") %>
        </div>
        <%# <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel', id:"file-ip-1-preview") %>
      <% end %>
      </div>
    </div>
  <% else %>
    <div class="col sticky-container">
    <div class="sticky-2 w-100 border shadow-sm rounded">
      <% if !@product.images.attached? %>
          <div class="display-img-vid-con" id="img-vid-con">
            <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel', id:"file-ip-1-preview") %>
          </div>
      <% end %>
      </div>
    </div>
  <% end %>
  <div class="col">
    <div class="mb-4">
      <%#  %>
      <%= form_with model: [:admin, @product] do |form| %>
        <% if product.errors.any? %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%# <strong>Holy guacamole!</strong> You should check in on some of those fields below. %>
                <div id="error_explanation">
                  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                  <ul>
                    <% product.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>

        <div class="mb-3 form">
          <%= form.label :images, class:"form-label" %>
          <%= form.file_field :images, accept:"image/*, video/*", id:"inp-img-vid", direct_upload: true, class:"form-control form-control-lg", multiple: true %>
        </div>

        <%# <div class="mb-3 form"> %>
          <%# <%= form.label :images, class:"form-label" %>
          <%# <%= form.file_field :images, direct_upload: true, class:"form-control form-control-lg", multiple: true %>
        <%# </div> %>

        <div class="form-floating mb-3">
          <%= form.text_field :name, class:"form-control", placeholder:"name" %>
          <%= form.label :name, class:"form-label" %>
        </div>

        <div class="form-floating mb-3">
          <%= form.number_field :price, class:"form-control", placeholder:"123" %>
          <%= form.label :price, class:"form-label" %>
        </div>

        <div class="form-floating mb-3">
          <%= form.text_area :description, class:"form-control", placeholder:"desc", style:"min-height:300px" %>
          <%= form.label :description, class:"form-label" %>
        </div>

        <div class="d-grid gap-2 col-6 mx-auto">
          <%= form.submit class:"btn btn-success" %>
        </div>
      <% end %>

    </div>
  </div>
</div>



<%# TEST %>
    <!-- button for selecting image/video -->
    <%# <label for="inp-img-vid">
      <span> Photos/Videos</span>
      <input type="file" accept="image/*, video/*" name="img-vid" id="inp-img-vid">
    </label> %>

    <%# <div class="display-img-vid-con" id="img-vid-con"  style="top: 30px; left: 250px;  position: absolute; z-index: 1" > %>
    <%# <div class="display-img-vid-con" id="img-vid-con"  style="top: 30px; left: 250px;  position: absolute; z-index: 1" >
    
      <!-- showing selected image here -->
      <!-- showing selected video here -->
    
    </div> %>
    <%# </div> %>

<%#  %>

<script>
  //$("#inp-img-vid").change( function(){ imgPreview(this); } );
  document.getElementById("inp-img-vid").addEventListener("change", onFileSelected, false);

  var tmpElement; //will be dynamically changed to Image or Video

  var file, file_ext, file_path, file_type, file_name;


  function show_Info_popUP()
  {
      alert("File is selected... " + "\n name : " + file_name  + "\n type : " + file_type + "\n ext : " + file_ext );
  }

  function onFileSelected ( input )
  {
  
      //if(input.files && input.files[0])
      if( input.target.files[0] )
      {
          file = input.target.files[0]; // FileList object
          
          file_ext; //# will extract file extension
          file_type = file.type; file_name = file.name;
          file_path = (window.URL || window.webkitURL).createObjectURL(file);
          
          //# get file extension (eg: "jpg" or "jpeg" or "webp" etc)
          file_ext = file_name.toLowerCase();
          file_ext = file_ext.substr( (file_ext.lastIndexOf(".")+1), (file_ext.length - file_ext.lastIndexOf(".")) );
          
          //# get file type (eg: "image" or "video")
          file_type = file_type.toLowerCase();
          file_type = file_type.substr( 0, file_type.indexOf("/") );
          
          let reader = new FileReader();
          reader.readAsDataURL(file);
          
          //reader.onload = function(e)
          reader.onloadend = function(evt) 
          { 
              //# POP-UP ...if you want to show (Alert box with) file details...
              // show_Info_popUP();
              
              if (evt.target.readyState == FileReader.DONE) 
              {
                  //# get container...
                  let container = document.getElementById("img-vid-con");
                  
                  //# remove any already existing child element(s)
                  while (container.firstChild)  
                  { container.removeChild(container.firstChild); }
                  
                  //# if IMAGE...
                  if ( file_type == "image" )
                  {
                      tmpElement = document.createElement( "img");
                      tmpElement.setAttribute("id", "preview-img");
                  }
                  
                  //# if VIDEO...
                  if ( file_type == "video" )
                  {
                      tmpElement = document.createElement( "video");
                      tmpElement.setAttribute("id", "preview-vid");
                      tmpElement.setAttribute("controls", "true" );
                      
                      tmpElement.addEventListener("loadeddata", () => 
                      {
                          //# what to do when some video data is loaded
                          
                          if (tmpElement.readyState >= 3) 
                          { 
                              //# what to do when video's first frame is ready
                              tmpElement.muted = true; //# if you want silent preview
                              tmpElement.play();
                          }
              
                      }); 
                  }
                  
                  //# finalise display size
                  // tmpElement.width = 640; tmpElement.height = 400;
                  
                  // tmpElement.style.maxWidth = '400px';
                  // tmpElement.style.objectFit = 'contain;';
                  // tmpElement.style.maxheight = '600px;';
                  // tmpElement.style.margin = '0px 50px 0px 50px';
                  
                  tmpElement.classList.add("img-carousel");
                  tmpElement.classList.add("w-100");
                  tmpElement.classList.add("d-block");
                  
                  tmpElement.setAttribute("src", file_path);
                  container.appendChild(tmpElement);
              }
          
          }
          
      }
  }
</script>

app/views/admin/products/_shop.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
    <% obj.order(id: :desc).each do |product| %>
        <div class="col">
            <div class="card h-100 card-hover">
            <%#  %>
                <div class="position-absolute top-0 start-0 m-1" style="z-index:1;">
                    <% if product.pre_order == true %>
                        <span class="badge rounded-pill text-bg-danger">Pre-Order</span>
                    <% end %>
                    <% if product.stock_product == true %>
                        <span class="badge rounded-pill text-bg-danger">Out of stock</span>
                    <% end %>
                </div>
            <%#  %>
                <div class="position-absolute top-0 end-0 m-1" style="z-index:2;">

                    <div class="dropdown dropstart">
                        <button class="btn btn-light" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Edit", edit_admin_product_path(product), class:"dropdown-item" %></li>
                            <li><%= link_to "Delete", admin_product_path(product), class:"dropdown-item", method: :delete, data: { confirm: 'Are you sure?' } %></li>
                        </ul>
                    </div>            

                </div>
                <%= link_to admin_product_path(product) do %>
                    <% if product.images.attached? %>
                        <% product.images.each_with_index do |image, index| %>
                            <% if index == 0 %>
                                <% if image.image? %>
                                    <%= image_tag(image, class:"card-img-top img-show") %>
                                <% elsif image.video? %>
                                    <video class="card-img-top img-show">
                                        <source src="<%= rails_blob_url(image) %>" type="<%= image.content_type %>"/>
                                    </video>
                                <% else %>
                                    Download: <%= link_to image.filename, rails_blob_path(image, disposition: "file") %>
                                <% end %>
                            <% end %>
                        <%# <img src="https://lpm.ulm.ac.id/image/desain/empty.jpg" class="card-img-top" alt="..."> %>
                        <% end %>
                        <%# <img src="https://lpm.ulm.ac.id/image/desain/empty.jpg" class="card-img-top" alt="..."> %>
                    <% else %>
                        <img src="https://lpm.ulm.ac.id/image/desain/empty.jpg" class="card-img-top img-show" alt="...">
                    <% end %>
                <% end %>

                <div class="card-body">
                    <h5 class="card-title"><%= link_to product.name, product, class:"text-decoration-none" %></h5>
                    <h6 class="card-subtitle mb-3 text-muted"><%= number_to_currency(product.price, unit: "Rp. ", separator: ",", delimiter: ".") %></h6>
                    <div class="row">
                        <div class="col">
                            <h6 class="card-subtitle mb-2 text-muted">
                                <%= product.keeps.count %> sold
                            </h6>
                        </div>
                        <div class="col text-end">
                            <h6 class="card-subtitle mb-2 text-muted">
                                <%= render "products/votes_score", product: product %>
                            </h6>
                        </div>
                    </div>
                    <div class="d-grid gap-2">
                        <%= link_to product.stock_product == true ? "Ready" : "Out of stock", admin_stock_path(product), method: :patch, class:product.stock_product == true ? "btn btn-warning" : "btn btn-danger" %>
                        <%= link_to product.pre_order == true ? "Direct order" : "Pre-Order", admin_preorder_path(product), method: :patch, class:product.pre_order == true ? "btn btn-warning" : "btn btn-danger" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/products/edit.html.erb
<div class="container-fluid px-4">
  <h1 class="text-center mt-4 mb-4">Editing Product</h1>
  <div>
    <div class="card mb-3 bg-light">
      <div class="card-body">
        <%= link_to 'View', admin_product_path(@product), class:"btn btn-lg btn-dark" %>
        <%= link_to 'Delete', admin_product_path(@product), class:"btn btn-lg btn-dark", method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to 'Back', :back, class:"float-end btn btn-lg btn-dark" %>
      </div>
    </div>
    <div class="mb-4">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Products</h1>
      <%# <%= search_form_for @q, class:"input-group mb-3" do |f| %>
      <%= search_form_for @q, url: search_admin_products_path, html: { method: :post } do |f| %>
        <div class="input-group">
          <%# <%= f.search_field :name_cont, class:"form-control", placeholder:"Search products" %>
          <%= f.search_field :name_or_description_cont, class:"form-control", placeholder:"Search products" %>
          <%= f.submit class:"btn btn-success" %>
        </div>
      <% end %>
    <div class="rounded bg-dark mb-3 mt-2">
    
      <ul class="nav nav-pills nav-fill">
      
      <%# <ul class="nav nav-pills nav-fill bg-dark rounded mb-3"> %>

        <li class="nav-item mb-4">
          <a class="nav-link">
            <%= sort_link(@q, :name, 'Name', class:"fs-4 decoration-hover text-white") %>
          </a>
        </li>
        
        <li class="nav-item mb-4">
          <a class="nav-link">
            <%= sort_link(@q, :price, 'Price', class:"fs-4 decoration-hover text-white") %>
          </a>
        </li>
        
        <li class="nav-item mb-4">
          <a class="nav-link">
            <%= sort_link(@q, :cached_votes_score, 'Like', class:"fs-4 decoration-hover text-white") %>
          </a>
        </li>

      
        <li class="nav-item mb-4">
          <a class="nav-link">
            <%= sort_link(@q, :created_at, 'Created', class:"fs-4 decoration-hover text-white") %>
          </a>
        </li>
      </ul>
    <%#  %>
  </div>

  <%= render 'shop', obj: @products %>

  <div class="d-flex justify-content-center">
    <%= paginate @products %>
  </div>
  <div class="text-center">
    <%= page_entries_info @products %>
  </div>
  <br>
</div>

app/views/admin/products/new.html.erb
<div class="container-fluid px-4">
    <h1 class="text-center mt-4 mb-4">New Product</h1>
    <div class="card mb-3 bg-light">
    
      <div class="card-body">
        <%= link_to 'Exit', admin_products_path, class:"btn btn-lg btn-dark" %>
        <%= link_to 'Back', :back, class:"float-end btn btn-lg btn-dark" %>
      </div>
    </div>
    <div class="mb-4">
      <%= render 'form', product: @product %>
    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container-fluid px-4">
  <div class="mt-4">
    <div class="card mb-3 bg-light">
      <div class="card-body">
        <%= link_to 'Edit', edit_admin_product_path(@product), class:"btn btn-lg btn-dark" %>
        <%= link_to 'Delete', admin_product_path(@product), class:"btn btn-lg btn-dark", method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to 'Exit', admin_products_path, class:"btn btn-lg btn-dark float-end" %>
      </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col sticky-container">
        <div class="sticky-2 w-100 border shadow-sm rounded">
            <% if @product.pre_order == true %>
              <div class="position-absolute top-0 start-0 m-1" style="z-index:1;">
                  <span class="badge rounded-pill text-bg-danger">Pre-Order</span>
              </div>
            <% end %>
            <% if @product.stock_product == true %>
              <div class="position-absolute top-0 end-0 m-1" style="z-index:1;">
                  <span class="badge rounded-pill text-bg-danger">Out of stock</span>
              </div>
            <% end %>
          <% @product.images.each_with_index do |c, index| %>
            <% if index > 0 %>
              <div class="carousel-dark">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            <% end %>
          <% end %>
          <% if @product.images.attached? %>
            <%= render 'products/carousel_product', obj: @product.images %>
          <% else %>
            <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel') %>
          <% end %>
        </div>
      </div>
      <div class="col">
        <div>
          <strong class="fs-1"><%= @product.name %></strong>
        </div>
        <div class="my-2 mb-2">
          <strong class="fs-4">
            <%= number_to_currency(@product.price, unit: "Rp. ", separator: ",", delimiter: ".") %>
          </strong>
        </div>

        <div class="row">
          <div class="col">
            <h6 class="card-subtitle mb-2 text-muted">
              <%= @keeps.count %> sold
            </h6>
          </div>
          <div class="col text-end">
            <h6 class="card-subtitle mb-2 text-muted">
              <%= render "products/votes_score", product: @product %>
            </h6>
          </div>
        </div>

        <div>
          <p class="justify-text">
            <%= simple_format(@product.description, style:"text-align:justify;") %>
          </p>
        </div>

        <div class="d-grid gap-2">
            <%= link_to @product.stock_product == true ? "Ready" : "Out of stock", admin_stock_path(@product), method: :patch, class:@product.stock_product == true ? "btn btn-warning" : "btn btn-danger" %>
            <%= link_to @product.pre_order == true ? "Direct order" : "Pre-Order", admin_preorder_path(@product), method: :patch, class:@product.pre_order == true ? "btn btn-warning" : "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
    <div class="d-flex justify-content-center row mb-4">
        <div class="col">
            <div class="d-flex flex-column comment-section">
              <h4>
                Comments (<%= @product.comments.count %>)
              </h4>
              <div class="bg-secondary p-2 rounded bg-opacity-25 mb-4">
                <%= render partial: 'comments/form', locals: { product: @product, parent: nil } %>
              </div>
                <%= render @product.comments.where(parent_id: nil).order(id: :desc) %>
              </div>
        </div>
    </div>
</div>

<%= render 'products/modal_product', obj: @product.images %>