config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms, except: :index
  resources :messages, only: %i[ new create ]
  resources :profiles, only: :show do
    member do
      post :upload_avatar
      delete :purge_avatar
    end
  end
  namespace :admin do
    resources :messages, only: %i[ new create ]
    resources :homepagesses, except: :index
    resources :abouts, except: %i[ show new ]
    resources :user_lists, except: :show
    resources :products do
      collection do
        match 'search' => 'products#search', via: [:get, :post], as: :search
      end
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
    end
    post 'faileds/removecart'
    post 'faileds/removebucket'
    post 'histories/add'
    post 'histories/remove'
    post 'faileds/add_cart'
    post 'faileds/add_bucket'
    post 'bucket/add'
    post 'bucket/remove'
    get 'failed', to: 'faileds#show'
    get 'bucket', to: 'bucket#show'
    get 'history', to: 'histories#show'
    get 'pages/dashboard'
    get 'pages/customer'
    get 'pages/adminlist'
    get 'pages/order'
    get 'pages/message'
    get 'pages/newadmin'
    get 'pages/chatroom/:chatroom_id', to: 'pages#chatroom', as: :chatroom
    get 'pages/chatbox', to: 'pages#chatbox', as: :chatbox
    patch "pages/adminlist/:id", to: "pages#add_admin"
    patch "products/stock/:id", to: "products#stock", as: :stock
    patch "products/preorder/:id", to: "products#preorder", as: :preorder
  end
  resources :products, only: %i[ show index ] do
      resources :comments do
        member do
          patch "like", to: "comments#like"
        end
      end
      member do
        patch "upvote", to: "products#upvote"
      end
  end
  post 'faileds/add'
  post 'cart/cart_update'
  post 'cart/addcart'
  post 'cart/add'
  post 'cart/removecart'
  post 'cart/remove'
  post 'cart/delete'
  get 'failed', to: 'faileds#show'
  get 'bucket', to: 'bucket#show'
  get 'history', to: 'histories#show'
  get 'cart', to: 'cart#show'
  get 'comments/comment'
  get 'pages/about'
  get 'pages/home'
  root 'pages#home'
  mount ActionCable.server, at: '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
    acts_as_votable
    belongs_to :user
    has_many_attached :images
    has_many :comments, dependent: :destroy
    has_many :orderables, dependent: :destroy
    has_many :carts, through: :orderables, dependent: :destroy

    # 
    has_many :vessels, dependent: :destroy
    has_many :keeps
    has_many :faileds
    # 

    validate :validate_images

    paginates_per 9

    validates :name, presence: true
    validates :price, presence: true

    # 
    # def set_quantity
    #     orderables.to_a.sum { |orderable| orderable.quantity }
    # end
    # 
  
    # extend FriendlyId
    # friendly_id :slug_candidates, use: [:slugged, :finders, :history]

    # def slug_candidates
    # [
    #     :name,
    #     [:name, :id]
    # ]
    # end

    # def should_generate_new_friendly_id?
    #     name_changed? || new_record? || slug.nil? || slug.blank?
    # end

    def new_method
        @order = orderables.first
        @order.images_status
    end

    private
    def validate_images
        return if images.count <= 10

        errors.add(:images, 'You can upload max 4 images')
    end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy stock preorder ]
    before_action :authenticate_user!
    before_action :restrict_user_by_role

    # GET /products or /products.json
    def index
      # @products = Product.all
      # @products = Product.order(cached_votes_score: :desc).page(params[:page])
      # 
      @q = Product.ransack(params[:q])
      @products = @q.result(distinct: true).order(cached_votes_score: :desc).page(params[:page])
    end

    def search
      index
      render :index
    end

    # GET /products/1 or /products/1.json
    def show
      # @keeps = Keep.all
      @keeps = @product.keeps.all
    end

    # GET /products/new
    def new
      @product = current_user.products.build
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = current_user.products.build(product_params)

      respond_to do |format|
        # 
        # if @product.images.count > 10
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json { render json: @product.errors, status: :unprocessable_entity }
        # else
        # 
          if @product.save
            format.html { redirect_to admin_product_url(@product), notice: "Product was successfully created." }
            format.json { render :show, status: :created, location: @product }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        # 
        # end
        # 
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        # 
        # if @product.images.count > 10
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json { render json: @product.errors, status: :unprocessable_entity }
        # else
        # 
          if @product.update(product_params)
            format.html { redirect_to admin_product_url(@product), notice: "Product was successfully updated." }
            format.json { render :show, status: :ok, location: @product }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        # 
        # end
        # 
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      # add_cart
      @product.destroy

      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def stock
      if @product.stock_product == true
        @product.update_attribute(:stock_product, false)
      elsif @product.stock_product == false
        @product.update_attribute(:stock_product, true)
      end
      redirect_to request.referrer
    end
    
    def preorder
      if @product.pre_order == true
        @product.update_attribute(:pre_order, false)
      elsif @product.pre_order == false
        @product.update_attribute(:pre_order, true)
      end
      redirect_to request.referrer
    end

    private
# 
    # def add_cart
    #   quantity = params[:quantity].to_i
    #   total_price = params[:total_price].to_i
    #   # order_end = params[:order_end].to_s
    #   order_start = params[:order_start].to_s
    #   customer = params[:customer].to_s
    #   product_price = params[:product_price].to_i
    #   product_name = params[:product_name].to_s
    #   product_id = params[:product_id].to_i 

    #   user_id = params[:user_id].to_i

    #   @failed = Failed.new(product_id: product_id, customer: customer, product_price: product_price, 
    #                        product_name: product_name, quantity: quantity, total_price: total_price,
    #                        order_start: order_start, user_id: user_id)
    #   if @failed.save
    #   #   removecart
    #   # else
    #     redirect_to request.referrer, notice: @failed.errors.full_messages.to_sentence
    #   end
    # end
# 

      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:name, :price, :description, images: [])
      end

    protected
    # redirect if user not logged in or does not have a valid role
      def restrict_user_by_role
        redirect_to root_path, notice: "You're not authorized!" if current_user.admin == false
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :upvote
  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).order(cached_votes_score: :desc).page(params[:page])
  end

  def upvote
  @product = Product.find(params[:id])
    if current_user.voted_up_on? @product
      @product.unvote_by current_user
    else
      @product.upvote_by current_user
    end
  render "vote.js.erb"
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    @keeps = @product.keeps.all
    # find current order in show page
    if user_signed_in?
      @showorder = @cart.orderables.find_by(product_id: @product.id)
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/1show.html.erb
<div class="container-fluid px-4">
  <div class="mt-4">
    <div class="card mb-3 bg-light">
      <div class="card-body">
      <%#  %>
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb float-start">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Library</a></li>
              <li class="breadcrumb-item active" aria-current="page">Data</li>
            </ol>
          </nav>
        </div>
        <div class="col">
          <%= link_to 'Exit', products_path, class:"btn btn-lg btn-dark float-end" %>
        </div>
      </div>
      <%#  %>
      </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col sticky-container bg-light bg-opacity-25">
        <div class="sticky-2 w-100 border shadow-sm rounded">
          <%#  %>
          <% @product.images.each_with_index do |c, index| %>
            <% if index > 0 %>
              <div class="carousel-dark">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            <% end %>
          <% end %>
          <%#  %>
          <% if @product.images.attached? %>
            <%= render 'products/carousel_product', obj: @product.images %>
          <% else %>
            <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel') %>
          <% end %>
          <%#  %>
        </div>
      </div>
      <div class="col">
        <div>
          <strong class="fs-1"><%= @product.name %></strong>
        </div>
        <div class="my-2 mb-2">
          <strong class="fs-4">
            <%= number_to_currency(@product.price, unit: "Rp. ", separator: ",", delimiter: ".") %>
          </strong>
        </div>

        <div>
          <%= @product.quantity %>
        </div>

        <div>
          <p>
            <%= simple_format(@product.description, style:"text-align:justify;") %>
          </p>
        </div>

        <%# start test %>
        <div data-turbo="true">
        <% if !@cart.orderables.find_by(product_id: @product.id).nil? %>
          <%= render 'products/cartupdate' %>
        <% end %>
        <%# <% else %> %>
        <% if @cart.orderables.find_by(product_id: @product.id).nil? %>
          <%= render 'products/cartadd' %>
        <% end %>
        </div>
        <%# end test %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
    <div class="d-flex justify-content-center row mb-4">
        <div class="col">
            <div class="d-flex flex-column comment-section">
              <h4>
                Comments (<%= @product.comments.count %>)
              </h4>
              <div class="bg-secondary p-2 rounded bg-opacity-25 mb-4">
                <%= render partial: 'comments/form', locals: { product: @product, parent: nil } %>
              </div>
                <%= render @product.comments.where(parent_id: nil).order(id: :desc) %>
              </div>
        </div>
    </div>
</div>

<%= render 'products/modal_product', obj: @product.images %>

app/views/products/ORIshow.html.erb
<div class="container-fluid px-4">
  <div class="mt-4">
    <div class="card mb-3 bg-light">
      <div class="card-body">
      <%#  %>
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb float-start">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Library</a></li>
              <li class="breadcrumb-item active" aria-current="page">Data</li>
            </ol>
          </nav>
        </div>
        <div class="col">
          <%= link_to 'Exit', products_path, class:"btn btn-lg btn-dark float-end" %>
        </div>
      </div>
      <%#  %>
      </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col sticky-container bg-light bg-opacity-25">
        <div class="sticky-2 w-100 border shadow-sm rounded">
          <%#  %>
          <% @product.images.each_with_index do |c, index| %>
            <% if index > 0 %>
              <div class="carousel-dark">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            <% end %>
          <% end %>
          <%#  %>
          <% if @product.images.attached? %>
            <%= render 'products/carousel_product', obj: @product.images %>
          <% else %>
            <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel') %>
          <% end %>
          <%#  %>
        </div>
      </div>
      <div class="col">
        <div>
          <strong class="fs-1"><%= @product.name %></strong>
        </div>
        <div class="my-2 mb-2">
          <strong class="fs-4">
            <%= number_to_currency(@product.price, unit: "Rp. ", separator: ",", delimiter: ".") %>
          </strong>
        </div>

        <div>
          <%= @product.quantity %>
        </div>

        <div>
          <p>
            <%= simple_format(@product.description, style:"text-align:justify;") %>
          </p>
        </div>

        <%# start test %>
        <%# <div data-turbo="true"> %>
        <% if !@showorder.nil? %>
              <div class="card">
              <div class="card-body">
              <h2>Order</h2>
            <%= form_with(url: cart_add_path) do |f| %>
              <%= f.hidden_field :id, value: @product.id %>
              <%= f.label :quantity, class:"form-label" %>
              <div class="mb-3">
                <%= f.number_field :quantity, value: @showorder.quantity, min: 1, class:"form-control" %>
              </div>
              <div class="mb-3">
                <%= f.label :description, 'Notes', class:"form-label" %>
                <%= f.text_area :description, value: @showorder.description, class:"form-control", placeholder:"Add notes here.." %>
              </div>
              <br><br>
              <%#  %>
                <%= f.submit "Update cart", class:"btn btn-warning position-absolute bottom-0 start-0 mb-4 ms-4" %>
            <% end %>
            <%# <div class=", class:"""> %>
            <%= form_with(url: cart_remove_path) do |f| %>
              <%= f.hidden_field :id, value: @showorder.id %>
                <div class="mb-3">
                  <%= f.submit "Cancel order", class:"btn btn-danger position-absolute bottom-0 end-0 mb-4 me-4" %>
                </div>
            <% end %>
              </div>
              </div>
              <%#  %>
        <% else %>
          <div class="card">
            <div class="card-body">
              <h2>Order</h2>
          <%= form_with(url: cart_add_path) do |f| %>
            <%= f.hidden_field :id, value: @product.id %>
            <%= f.label :quantity, class:"form-label" %>
            <div class="mb-3">
              <%= f.number_field :quantity, value: 0, min: 1, class:"form-control" %>
            </div>
            <div class="mb-3">
              <%= f.label :description, 'Notes', class:"form-label" %>
              <%= f.text_area :description, class:"form-control", placeholder:"Add notes here.." %>
            </div>
            <br><br>
              <%= f.submit "Add to cart", class:"btn btn-primary position-absolute bottom-0 start-0 mb-4 ms-4" %>
          <% end %>
            </div>
          </div>
        <% end %>
        <%# </div> %>
        <%# end test %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
    <div class="d-flex justify-content-center row mb-4">
        <div class="col">
            <div class="d-flex flex-column comment-section">
              <h4>
                Comments (<%= @product.comments.count %>)
              </h4>
              <div class="bg-secondary p-2 rounded bg-opacity-25 mb-4">
                <%= render partial: 'comments/form', locals: { product: @product, parent: nil } %>
              </div>
                <%= render @product.comments.where(parent_id: nil).order(id: :desc) %>
              </div>
        </div>
    </div>
</div>

<%= render 'products/modal_product', obj: @product.images %>

app/views/products/_shop.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
    <% obj.order(id: :desc).where(stock_product: false).each do |product| %>
        <div class="col">
            <div class="card h-100 card-hover">
            <% if product.pre_order == true %>
                <div class="position-absolute top-0 start-0 m-1" style="z-index:2;">
                    <span class="badge rounded-pill text-bg-primary">Pre-Order</span>
                </div>
            <% end %>
            <% if user_signed_in? %>
            <div class="position-absolute top-0 end-0 m-1" style="z-index:2;">
                <%= render "products/upvote_link", product: product %>
            </div>
            <% else %>
                <div class="position-absolute top-0 end-0 m-1" style="z-index:2;">
                    <%= link_to upvote_product_path(product), method: :patch do %>
                        <h3 class="border-like-false">
                            <i class="bi bi-heart-fill"></i>
                        </h3>
                    <% end %>
                </div>
            <% end %>
                <%= link_to product_path(product) do %>
                    <% if product.images.attached? %>
                        <% product.images.each_with_index do |image, index| %>
                            <% if index == 0 %>
                                <% if image.image? %>
                                    <%= image_tag(image, class:"card-img-top img-show") %>
                                <% elsif image.video? %>
                                    <video class="card-img-top img-show">
                                        <source src="<%= rails_blob_url(image) %>" type="<%= image.content_type %>"/>
                                    </video>
                                <% else %>
                                    Download: <%= link_to image.filename, rails_blob_path(image, disposition: "file") %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% else %>
                        <img src="https://lpm.ulm.ac.id/image/desain/empty.jpg" class="card-img-top img-show" alt="...">
                    <% end %>
                <% end %>

                <div class="card-body">
                    <h5 class="card-title"><%= link_to product.name, product, class:"text-decoration-none" %></h5>
                    <h6 class="card-subtitle mb-3 text-muted"><%= number_to_currency(product.price, unit: "Rp. ", separator: ",", delimiter: ".") %></h6>
                    <div class="row">
                        <div class="col">
                            <h6 class="card-subtitle mb-2 text-muted">
                                <%= product.keeps.count %> sold
                            </h6>
                        </div>
                        <div class="col text-end">
                            <h6 class="card-subtitle mb-2 text-muted">
                                <%= render "products/votes_score", product: product %>
                            </h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/products/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{product.id}" do %>
  <%= link_to upvote_product_path(product), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <%# <%= link_to upvote_product_path(product), method: :patch, remote: true do %> 
    <% if current_user.voted_up_on? product %>
      <%# unvote %>
      <h3 class="border-like-true">
        <i class="bi bi-heart-fill"></i>
      </h3>
    <% else %>
      <%# vote! %>
      <h3 class="border-like-false">
        <i class="bi bi-heart-fill"></i>
        <%# <i class="bi bi-heart"></i> %>
      </h3>
    <% end %>
  <% end %>
<% end %>

app/views/products/_votes_score.html.erb
<%= content_tag "div", id: "votes-score-#{product.id}" do %>
  <%= product.cached_votes_score %> likes
<% end %>

app/views/products/show.html.erb
<div class="container-fluid px-4">
<%#  %>
  <div class="mt-4">
    <div class="card mb-3 bg-light">
      <div class="card-body">
      <%#  %>
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb float-start">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <%= link_to 'Products', products_path %>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                <%= @product.name %>
              </li>
            </ol>
          </nav>
        </div>
        <div class="col">
          <%= link_to 'Exit', products_path, class:"btn btn-lg btn-dark float-end" %>
        </div>
      </div>
      <%#  %>
      </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col sticky-container">
        <div class="sticky-2 w-100 border shadow-sm rounded">
            <% if @product.pre_order == true %>
              <div class="position-absolute top-0 start-0 m-1" style="z-index:1;">
                  <span class="badge rounded-pill text-bg-primary">Pre-Order</span>
              </div>
            <% end %>
        <%#  %>
        <% if user_signed_in? %>
            <div class="position-absolute top-0 end-0 m-2" style="z-index:2;">
                <%= render "products/upvote_link", product: @product %>
            </div>
            <% else %>
                <%# <%= link_to upvote_product_path(product), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
                <div class="position-absolute top-0 end-0 m-2" style="z-index:2;">
                    <%= link_to upvote_product_path(@product), method: :patch do %>
                        <h3 class="border-like-false">
                            <i class="bi bi-heart-fill"></i>
                        </h3>
                    <% end %>
                </div>
                <%# <% end %>
            <% end %>
        <%#  %>
          <%#  %>
          <% @product.images.each_with_index do |c, index| %>
            <% if index > 0 %>
              <div class="carousel-dark">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            <% end %>
          <% end %>
          <%#  %>
          <% if @product.images.attached? %>
            <%= render 'products/carousel_product', obj: @product.images %>
          <% else %>
            <%= image_tag('https://lpm.ulm.ac.id/image/desain/empty.jpg', class:'d-block w-100 img-carousel') %>
          <% end %>
          <%#  %>
        </div>
      </div>
      <div class="col">
        <div>
          <strong class="fs-1"><%= @product.name %></strong>
        </div>
        <div class="my-2 mb-2">
          <strong class="fs-4">
            <%= number_to_currency(@product.price, unit: "Rp. ", separator: ",", delimiter: ".") %>
          </strong>
        </div>

        <div class="row">
          <div class="col">
            <h6 class="card-subtitle mb-2 text-muted">
              <%= @keeps.count %> sold
            </h6>
          </div>
          <div class="col text-end">
            <h6 class="card-subtitle mb-2 text-muted">
              <%= render "products/votes_score", product: @product %>
            </h6>
          </div>
        </div>

        <div>
          <p>
            <%= simple_format(@product.description, style:"text-align:justify;") %>
          </p>
        </div>

        <%# start test %>
        <%# <div data-turbo="true"> %>
        <% if !@showorder.nil? %>
              <div class="card">
              <div class="card-body">
              <h2>Order</h2>
              <% if user_signed_in? %>
                <% if !@product.orderables.empty? && @product.new_method == false %>
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Waiting for confirmation...
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                <% end %>
              <% end %>
            <%= form_with(url: cart_add_path) do |f| %>
              <%= f.hidden_field :id, value: @product.id %>
              <%= f.label :quantity, class:"form-label" %>
              <div class="mb-3">
                <%= f.number_field :quantity, value: @showorder.quantity, min: 1, class:"form-control" %>
              </div>
              <div class="mb-3">
                <%= f.label :description, 'Notes', class:"form-label" %>
                <%= f.text_area :description, value: @showorder.description, class:"form-control", placeholder:"Add notes here.." %>
              </div>
              <br><br>
              <%#  %>
              <%= f.submit "Update cart", class: !@product.orderables.empty? && @product.new_method == false ? "btn btn-warning position-absolute bottom-0 start-0 mb-4 ms-4 disabled" : "btn btn-warning position-absolute bottom-0 start-0 mb-4 ms-4" %>
            <% end %>
            <%# <div class=", class:"""> %>
            <%= form_with(url: cart_remove_path) do |f| %>
              <%= f.hidden_field :id, value: @showorder.id %>
                <div class="mb-3">
                  <%= f.submit "Cancel order", class: !@product.orderables.empty? && @product.new_method == false ? "btn btn-danger position-absolute bottom-0 end-0 mb-4 me-4 disabled" : "btn btn-danger position-absolute bottom-0 end-0 mb-4 me-4" %>
                </div>
            <% end %>
              </div>
              </div>
              <%#  %>
        <% else %>
          <div class="card">
            <div class="card-body">
              <h2>Order</h2>
              <%#  %>
              <% if user_signed_in? %>
                <% unless current_user.firstname? && current_user.my_address? && current_user.phone? || current_user.wa_phone? %>
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Complete your profile data!</strong> You should complete your profile data <%= link_to 'here', edit_user_registration_path %> if you want to order.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                <% end %>
              <% end %>
              <%#  %>
          <%= form_with(url: cart_add_path) do |f| %>
            <%= f.hidden_field :id, value: @product.id %>
            <%= f.label :quantity, class:"form-label" %>
            <div class="mb-3">
              <%= f.number_field :quantity, value: 0, min: 1, class:"form-control" %>
            </div>
            <div class="mb-3">
              <%= f.label :description, 'Notes', class:"form-label" %>
              <%= f.text_area :description, class:"form-control", placeholder:"Add notes here.." %>
            </div>
            <br><br>
              <%= f.submit "Add to cart", class:"btn btn-primary position-absolute bottom-0 start-0 mb-4 ms-4" %>
          <% end %>
            </div>
          </div>
        <% end %>
        <%# </div> %>
        <%# end test %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
    <div class="d-flex justify-content-center row mb-4">
        <div class="col">
            <div class="d-flex flex-column comment-section">
              <h4>
                Comments (<%= @product.comments.count %>)
              </h4>
              <div class="bg-secondary p-2 rounded bg-opacity-25 mb-4">
                <%= render partial: 'comments/form', locals: { product: @product, parent: nil } %>
              </div>
                <%= render @product.comments.where(parent_id: nil).order(id: :desc) %>
              </div>
        </div>
    </div>
</div>

<%= render 'products/modal_product', obj: @product.images %>

app/views/products/vote.js.erb
document.getElementById("upvote-<%= @product.id %>").innerHTML = "<%= j render "products/upvote_link", product: @product %>";
document.getElementById("votes-score-<%= @product.id %>").innerHTML = "<%= j render "products/votes_score", product: @product %>";